// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Optimisarr.Data;

#nullable disable

namespace Optimisarr.Data.Migrations
{
    [DbContext(typeof(OptimisarrDbContext))]
    [Migration("20260904065844_AddFrameRateCap")]
    partial class AddFrameRateCap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Optimisarr.Data.ActivityWatcher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiToken")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RefreshOnReplace")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ActivityWatchers");
                });

            modelBuilder.Entity("Optimisarr.Data.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("Optimisarr.Data.ArrConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArrConnections");
                });

            modelBuilder.Entity("Optimisarr.Data.Exclusion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Exclusions");
                });

            modelBuilder.Entity("Optimisarr.Data.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdaptiveVideoQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalibrationClipSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CalibrationClipStartSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CalibrationReferenceStartSeconds")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("CalibrationSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedCrop")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EffectiveVideoQuality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnqueueReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCategory")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FfmpegArguments")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IgnoreMediaActivity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OutputSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessLog")
                        .HasColumnType("TEXT");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<int>("QualityRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestedAudioBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestedImageQuality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedRuleProfile")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedVideoQuality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceSha256")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("VerificationPassed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VerificationReportJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoEncoder")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoQualityMode")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkOutputPath")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CalibrationSessionId");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("Status");

                    b.HasIndex("Priority", "EnqueuedAt");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Optimisarr.Data.JobLease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasFilter("\"State\" = 'Held'");

                    b.HasIndex("WorkerId");

                    b.ToTable("JobLeases");
                });

            modelBuilder.Entity("Optimisarr.Data.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioClippingGateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AudioLoudnessGateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioTargetCodec")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoEnqueueEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("AutoEnqueueWindowEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly>("AutoEnqueueWindowStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoReplace")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ClipVmafEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTune")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CropBlackBars")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DownmixToStereo")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationTolerancePercent")
                        .HasColumnType("REAL");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EncoderPreset")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExcludeHardLinkedFiles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExcludePaths")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("HdrHandling")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageDownscaleMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageDownscaleValue")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImageMetadataGateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ImageQuality")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ImageQualityGateEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeepAudioLanguages")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeepSubtitleLanguages")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastAutoEnqueueAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxFrameRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxLoudnessDriftLufs")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxTruePeakDbtp")
                        .HasColumnType("REAL");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MinFileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinVmafCatastrophicMin")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinVmafHarmonicMean")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinVmafMin")
                        .HasColumnType("REAL");

                    b.Property<double>("MinimumImageSsim")
                        .HasColumnType("REAL");

                    b.Property<bool>("MoveOnComplete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MoveOverwrite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OptimiseDolbyVision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualityCrf")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReencodeLossyAudio")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReencodeLossyImages")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ReencodeSameCodecAboveBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireAudioRetained")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireSizeReduction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequireSubtitlesRetained")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuleProfile")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SkipEfficientSources")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkipSourceCodecs")
                        .HasColumnType("TEXT");

                    b.Property<bool>("StrongerAdaptiveQuantisation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetContainer")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetFolder")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetImageFormat")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetVideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoAudioBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoAudioCodec")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoDownscaleHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VideoQualityStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VmafFrameSubsample")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("VmafQualityGateEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Optimisarr.Data.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttachedPictureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AudioBitrateKbps")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodecs")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioLanguages")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BitsPerRawSample")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Container")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DiscoveredAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrameCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HardLinkCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDolbyVision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHdr")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVariableFrameRate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MediaKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OptimisedMarker")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProbeError")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProbedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubtitleLanguages")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SubtitleTrackCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoProfile")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("LibraryId", "RelativePath");

                    b.ToTable("MediaFiles");
                });

            modelBuilder.Entity("Optimisarr.Data.NotificationTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOnFailure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotifyOnReplacement")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Token")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationTargets");
                });

            modelBuilder.Entity("Optimisarr.Data.Replacement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CrossFilesystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FinalPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NewSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<long>("OriginalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("PurgedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuarantinePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReplacedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RolledBackAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("Status");

                    b.ToTable("Replacements");
                });

            modelBuilder.Entity("Optimisarr.Data.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CredentialFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("FreeScratchBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HardwareDecoders")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PairedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoEncoders")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vmaf")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CredentialFingerprint")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Optimisarr.Data.Job", b =>
                {
                    b.HasOne("Optimisarr.Data.MediaFile", "MediaFile")
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("Optimisarr.Data.JobLease", b =>
                {
                    b.HasOne("Optimisarr.Data.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Optimisarr.Data.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Optimisarr.Data.MediaFile", b =>
                {
                    b.HasOne("Optimisarr.Data.Library", "Library")
                        .WithMany("MediaFiles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Optimisarr.Data.Replacement", b =>
                {
                    b.HasOne("Optimisarr.Data.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Optimisarr.Data.Library", b =>
                {
                    b.Navigation("MediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
